# Generated by Django 3.0.4 on 2020-04-26 15:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('IN', 'Individual'), ('CO', 'Company'), ('OT', 'Other')], default='IN', max_length=2)),
                ('first_name', models.CharField(blank=True, default='first name', max_length=256)),
                ('last_name', models.CharField(blank=True, default='last name', max_length=256)),
                ('company_name', models.CharField(blank=True, default='company name', max_length=256)),
                ('melli_code', models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only anumeric characters are allowed.')])),
                ('tel1', models.CharField(default='XXXXXXXX', max_length=256)),
                ('tel2', models.CharField(blank=True, default='XXXXXXXX', max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(default='address', max_length=512)),
                ('postcode', models.CharField(default='XXXXXXXXXX', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melli_code', models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only anumeric characters are allowed.')])),
                ('first_name', models.CharField(blank=True, default='first name', max_length=256)),
                ('last_name', models.CharField(blank=True, default='last name', max_length=256)),
                ('driver_code', models.CharField(default=0, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only anumeric characters are allowed.')])),
                ('tel1', models.CharField(default='XXXXXXXX', max_length=256)),
                ('number_plate_1', models.CharField(default=0, max_length=2, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only anumeric characters are allowed.')])),
                ('number_plate_letter', models.CharField(choices=[('01', 'الف'), ('02', 'ب'), ('03', 'پ'), ('04', 'ت'), ('05', 'ث'), ('06', 'ج'), ('07', 'چ'), ('08', 'ح'), ('09', 'خ'), ('10', 'د'), ('11', 'ذ'), ('12', 'ر'), ('13', 'ز'), ('14', 'ژ'), ('15', 'س'), ('16', 'ش'), ('17', 'ص'), ('18', 'ض'), ('19', 'ط'), ('20', 'ظ'), ('21', 'ع'), ('22', 'غ'), ('23', 'ف'), ('24', 'ق'), ('24', 'ک'), ('25', 'گ'), ('26', 'ل'), ('27', 'م'), ('28', 'ن'), ('29', 'و'), ('30', 'ه'), ('31', 'ی')], default='000', max_length=2)),
                ('number_plate_2', models.CharField(default=0, max_length=3, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only anumeric characters are allowed.')])),
                ('number_plate_iran', models.CharField(default=0, max_length=2, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only anumeric characters are allowed.')])),
                ('truck_size', models.CharField(choices=[('MOT', 'Motorbike - موتور'), ('CAR', 'Car - سواری'), ('VAN', 'Vanet peykan - وانت پیکان'), ('NIS', 'Nissan - نیسان'), ('ISU', 'ISUZU - ایسوزو'), ('KHA', 'KHAVAR - خاور'), ('BUD', 'BUDSAN - بادسان'), ('TAK', 'TAK - تک'), ('JOF', 'JOFT - جفت'), ('20F', '20ft container - کانتینر ۲۰ فوت'), ('40F', '40ft container - کانتینر ۴۰ فوت'), ('40H', '40ft hi container  - کانتینر ۴۰ فوت های'), ('FBT', 'Flat bed trailer - تریلی کفی'), ('SRT', 'Side raised trailer - تریلی بغلدار'), ('TRT', 'Transit trailer  - تریلی ترانزیتی')], default='ON', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_order_no', models.PositiveIntegerField(blank=True, null=True)),
                ('order_type', models.CharField(choices=[('IN', 'Inbound'), ('OU', 'Outbound'), ('TR', 'Transfer ')], default='ON', max_length=10)),
                ('permit_type', models.CharField(choices=[('PAP', 'Paper'), ('FAX', 'Fax'), ('EMA', 'Email'), ('TEL', 'Telephone')], default='ON', max_length=10)),
                ('permit_number', models.CharField(default='0', max_length=30, null=True)),
                ('notes', models.TextField(blank=True, default='some notes', max_length=2048)),
                ('origin_destination', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('billway_number', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('transport_company', models.CharField(blank=True, default='company name', max_length=256)),
                ('sender_receiver', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('OFF', 'Off - inactive'), ('ON', 'On - active')], default='ON', max_length=20)),
                ('invalidated', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='set_app.Customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='set_app.Driver')),
                ('receiving_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_customer', to='set_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='product code', max_length=30, unique=True)),
                ('barcode', models.CharField(default=0, max_length=30, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only anumeric characters are allowed.')])),
                ('name', models.CharField(default='product name', max_length=128)),
                ('description', models.CharField(blank=True, default='some description', max_length=512)),
                ('brand', models.CharField(default='product brand', max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OFF', 'Off - inactive'), ('ON', 'On - active')], default='ON', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StorageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Storage Tag Name', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='warehouse name', max_length=256)),
                ('tel1', models.CharField(default='XXXXXXXX', max_length=256)),
                ('tel2', models.CharField(default='XXXXXXXX', max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(default='address', max_length=512)),
                ('postcode', models.CharField(default='XXXXXXXXXX', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='09XXXXXXXXX', max_length=11)),
                ('melli_code', models.CharField(default='XXXXXXXXXX', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='set_app.Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='set_app.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='set_app.Warehouse'),
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField()),
                ('total', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('invalidated', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='set_app.Customer')),
                ('order_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='set_app.OrderItem')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='set_app.Product')),
                ('warehouse', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='set_app.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='set_app.Customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='set_app.Product')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='set_app.Warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='storage_tags',
            field=models.ManyToManyField(to='set_app.StorageTag'),
        ),
        migrations.AddField(
            model_name='customer',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='set_app.Warehouse'),
        ),
    ]
