# Generated by Django 3.0.4 on 2020-04-01 19:56

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('set_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='number_plate',
        ),
        migrations.AddField(
            model_name='driver',
            name='number_plate_1',
            field=models.CharField(default=0, max_length=3, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only anumeric characters are allowed.')]),
        ),
        migrations.AddField(
            model_name='driver',
            name='number_plate_2',
            field=models.CharField(choices=[('الف', 'الف'), ('ب', 'ب'), ('پ', 'پ'), ('ت', 'ت'), ('ث', 'ث'), ('ج', 'ج'), ('چ', 'چ'), ('ح', 'ح'), ('خ', 'خ'), ('د', 'د'), ('ذ', 'ذ'), ('ر', 'ر'), ('ز', 'ز'), ('ژ', 'ژ'), ('س', 'س'), ('ش', 'ش'), ('ص', 'ص'), ('ض', 'ض'), ('ط', 'ط'), ('ظ', 'ظ'), ('ع', 'ع'), ('غ', 'غ'), ('ف', 'ف'), ('ک', 'ک'), ('گ', 'گ'), ('ل', 'ل'), ('م', 'م'), ('ن', 'ن'), ('و', 'و'), ('ه', 'ه'), ('ی', 'ی')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='number_plate_3',
            field=models.CharField(default=0, max_length=2, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only anumeric characters are allowed.')]),
        ),
        migrations.AddField(
            model_name='driver',
            name='number_plate_4',
            field=models.CharField(default=0, max_length=2, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only anumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='truck_size',
            field=models.CharField(choices=[('MOT', 'Motorbike - موتور'), ('CAR', 'Car - سواری'), ('VAN', 'Vanet peykan - وانت پیکان'), ('NIS', 'Nissan - نیسان'), ('ISU', 'ISUZU - ایسوزو'), ('KHA', 'KHAVAR - خاور'), ('BUD', 'BUDSAN - بادسان'), ('TAK', 'TAK - تک'), ('JOF', 'JOFT - جفت'), ('20F', '20 Foot container - کانتینر ۲۰ فوت'), ('40F', '40 Foot container - کانتینر ۴۰ فوت'), ('40H', '40 Foot HIGH container  - کانتینر ۴۰ فوت های'), ('FBT', 'Flat bed trailer - تریلی کفی'), ('SRT', 'Side raised trailer - تریلی بغلدار'), ('TRT', 'Transit trailer  - تریلی ترانزیتی')], default='ON', max_length=100),
        ),
    ]
