# Generated by Django 3.0.4 on 2020-04-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='truck_size',
            field=models.CharField(choices=[('MOT', 'Motorbike - موتور'), ('CAR', 'Car - سواری'), ('VAN', 'Vanet peykan - وانت پیکان'), ('NIS', 'Nissan - نیسان'), ('ISU', 'ISUZU - ایسوزو'), ('KHA', 'KHAVAR - خاور'), ('BUD', 'BUDSAN - بادسان'), ('TAK', 'TAK - تک'), ('JOF', 'JOFT - جفت'), ('20F', '20ft container - کانتینر ۲۰ فوت'), ('40F', '40ft container - کانتینر ۴۰ فوت'), ('40H', '40ft high container  - کانتینر ۴۰ فوت های'), ('FBT', 'Flat bed trailer - تریلی کفی'), ('SRT', 'Side raised trailer - تریلی بغلدار'), ('TRT', 'Transit trailer  - تریلی ترانزیتی')], default='ON', max_length=100),
        ),
    ]
