# Generated by Django 3.0.4 on 2020-04-01 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_app', '0002_auto_20200401_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='number_plate_3',
            new_name='number_plate_iran',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='number_plate_4',
        ),
        migrations.AddField(
            model_name='driver',
            name='number_plate_letter',
            field=models.CharField(choices=[('الف', 'الف'), ('ب', 'ب'), ('پ', 'پ'), ('ت', 'ت'), ('ث', 'ث'), ('ج', 'ج'), ('چ', 'چ'), ('ح', 'ح'), ('خ', 'خ'), ('د', 'د'), ('ذ', 'ذ'), ('ر', 'ر'), ('ز', 'ز'), ('ژ', 'ژ'), ('س', 'س'), ('ش', 'ش'), ('ص', 'ص'), ('ض', 'ض'), ('ط', 'ط'), ('ظ', 'ظ'), ('ع', 'ع'), ('غ', 'غ'), ('ف', 'ف'), ('ک', 'ک'), ('گ', 'گ'), ('ل', 'ل'), ('م', 'م'), ('ن', 'ن'), ('و', 'و'), ('ه', 'ه'), ('ی', 'ی')], default='الف', max_length=3),
        ),
        migrations.AlterField(
            model_name='driver',
            name='number_plate_2',
            field=models.CharField(default=0, max_length=2, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only anumeric characters are allowed.')]),
        ),
    ]
