# Generated by Django 3.0.4 on 2020-03-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_app', '0002_userprofileinfo_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='melli_code',
            field=models.IntegerField(default='0000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='mobile',
            field=models.IntegerField(default='09000000000', max_length=11),
        ),
    ]
