# Generated by Django 3.0.4 on 2020-04-13 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('set_app', '0002_auto_20200411_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='truck_size',
            field=models.CharField(choices=[('MOT', 'Motorbike - موتور'), ('CAR', 'Car - سواری'), ('VAN', 'Vanet peykan - وانت پیکان'), ('NIS', 'Nissan - نیسان'), ('ISU', 'ISUZU - ایسوزو'), ('KHA', 'KHAVAR - خاور'), ('BUD', 'BUDSAN - بادسان'), ('TAK', 'TAK - تک'), ('JOF', 'JOFT - جفت'), ('20F', '20ft container - کانتینر ۲۰ فوت'), ('40F', '40ft container - کانتینر ۴۰ فوت'), ('40H', '40ft hi container  - کانتینر ۴۰ فوت های'), ('FBT', 'Flat bed trailer - تریلی کفی'), ('SRT', 'Side raised trailer - تریلی بغلدار'), ('TRT', 'Transit trailer  - تریلی ترانزیتی')], default='ON', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiving_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_customer', to='set_app.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('OFF', 'Off - inactive'), ('ON', 'On - active')], default='ON', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='sys_order_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
