# Generated by Django 3.0.4 on 2020-04-13 17:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('set_app', '0003_auto_20200413_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='number_plate_1',
            field=models.CharField(default=0, max_length=2, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only anumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='number_plate_2',
            field=models.CharField(default=0, max_length=3, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only anumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='number_plate_letter',
            field=models.CharField(choices=[('01', 'الف'), ('02', 'ب'), ('03', 'پ'), ('04', 'ت'), ('05', 'ث'), ('06', 'ج'), ('07', 'چ'), ('08', 'ح'), ('09', 'خ'), ('10', 'د'), ('11', 'ذ'), ('12', 'ر'), ('13', 'ز'), ('14', 'ژ'), ('15', 'س'), ('16', 'ش'), ('17', 'ص'), ('18', 'ض'), ('19', 'ط'), ('20', 'ظ'), ('21', 'ع'), ('22', 'غ'), ('23', 'ف'), ('24', 'ق'), ('24', 'ک'), ('25', 'گ'), ('26', 'ل'), ('27', 'م'), ('28', 'ن'), ('29', 'و'), ('30', 'ه'), ('31', 'ی')], default='000', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='set_app.Driver'),
        ),
    ]
