# Generated by Django 3.0.4 on 2020-03-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_app', '0003_auto_20200319_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='melli_code',
            field=models.CharField(default='XXXXXXXXXX', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='mobile',
            field=models.CharField(default='09XXXXXXXXX', max_length=11),
        ),
    ]
