# Generated by Django 3.0.4 on 2020-04-02 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('set_app', '0003_auto_20200401_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='set_app.Driver'),
        ),
        migrations.AlterField(
            model_name='order',
            name='permit_number',
            field=models.CharField(default='0', max_length=30, null=True),
        ),
    ]
