# Generated by Django 3.0.4 on 2020-04-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_app', '0004_auto_20200413_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billway_number',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='origin_destination',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender_receiver',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
