# Generated by Django 3.0.4 on 2020-03-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('set_app', '0004_auto_20200319_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='warehouse name', max_length=256)),
                ('tel1', models.CharField(default='XXXXXXXX', max_length=256)),
                ('tel2', models.CharField(default='XXXXXXXX', max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(default='address', max_length=512)),
                ('postcode', models.CharField(default='XXXXXXXXXX', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='first name', max_length=256)),
                ('last_name', models.CharField(default='last name', max_length=256)),
                ('company_name', models.CharField(default='company name', max_length=256)),
                ('tel1', models.CharField(default='XXXXXXXX', max_length=256)),
                ('tel2', models.CharField(default='XXXXXXXX', max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(default='address', max_length=512)),
                ('postcode', models.CharField(default='XXXXXXXXXX', max_length=10)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='set_app.Warehouse')),
            ],
        ),
    ]
