# Generated by Django 3.0.4 on 2020-03-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_app', '0005_customer_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.IntegerField(choices=[(1, 'INDIVIDUAL'), (2, 'COMPANY'), (3, 'OTHER')], default=1),
        ),
    ]
