# Generated by Django 3.0.4 on 2020-03-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_app', '0007_auto_20200326_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='entity_type',
            field=models.CharField(choices=[('IN', 'Individual'), ('CO', 'Company'), ('OT', 'Other')], default='IN', max_length=2),
        ),
    ]
