# Generated by Django 3.0.4 on 2020-03-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_app', '0008_auto_20200326_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='product code', max_length=256)),
                ('name', models.CharField(default='product name', max_length=256)),
                ('description', models.CharField(default='some description', max_length=256)),
                ('barcode', models.IntegerField()),
                ('brand', models.CharField(default='product brand', max_length=256)),
                ('status', models.CharField(choices=[('OFF', 'Off - inactive'), ('ON', 'On - active')], default='ON', max_length=256)),
            ],
        ),
    ]
