# Generated by Django 3.0.4 on 2020-03-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_app', '0009_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='product brand', max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default='product code', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='some description', max_length=512),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product name', max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('OFF', 'Off - inactive'), ('ON', 'On - active')], default='ON', max_length=20),
        ),
    ]
